// UserPage
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const REMOVE_USER = 'REMOVE_USER';

// Posts
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const REMOVE_USER_POSTS = 'REMOVE_USER_POSTS';
export const GET_USER_POST = 'GET_USER_POST';
export const REMOVE_USER_POST = 'REMOVE_USER_POST';
export const ADD_NEW_USER_POST = 'ADD_NEW_USER_POST';
export const DELETE_USER_POST = 'DELETE_USER_POST';

// Comments
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const REMOVE_POST_COMMENTS = 'REMOVE_POST_COMMENTS';
export const ADD_NEW_POST_COMMENT = 'ADD_NEW_POST_COMMENT';
export const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT';
